import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { useRouter } from 'next/router';

import { api } from "../utils/api";

const Home: NextPage = () => {
  const session = useSession();
  console.log(session)
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const router = useRouter();

  return (
    <>
      <Head>
        <title>FileCaptainLanding</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-start justify-start bg-gradient-to-b from-[#692f00] to-[#15162c]">
        <div className="container flex flex-col items-start justify-start gap-03 px-5 py-2 ">
          <h1 className="text-7xl font-extrabold tracking-tight text-black sm:text-[6rem]">
            File <span className="text-[hsl(0,64%,18%)]">Captain</span> .io
          </h1>
        </div>
        <img className="w-16 md:w-32 lg:w-48 h-32 rounded-full mx-auto" src="/iconlogo.png" alt="" width="384" height="512"></img>
      </main>
    </>
  );
};

export default Home;